
<template>
  <AdminShell title="产品系列管理" subtitle="选择所属分类，维护系列内容及发布状态。">
    <div class="toolbar"><label>所属分类 <select v-model.number="categoryFilter" @change="load"><option :value="0">全部分类</option><option v-for="item in categories" :key="Number(item.id)" :value="Number(item.id)">{{ item.name_zh }}</option></select></label><button @click="startNew">新建系列</button></div>
    <div class="layout">
      <form class="card form" @submit.prevent="submit"><h2>{{ editingId ? "编辑系列" : "新建系列" }}</h2><label><span>所属分类 <span class="required-mark" aria-hidden="true">*</span></span><select v-model.number="form.categoryId" required><option v-for="item in categories" :key="Number(item.id)" :value="Number(item.id)">{{ item.name_zh }}</option></select></label><label><span>系列名称（中文） <span class="required-mark" aria-hidden="true">*</span></span><input v-model.trim="form.nameZh" required /></label><label><span>系列名称（英文） <span class="required-mark" aria-hidden="true">*</span></span><input v-model.trim="form.nameEn" required /></label><label>系列简介（中文） <textarea v-model.trim="form.summaryZh" /></label><label>系列简介（英文） <textarea v-model.trim="form.summaryEn" /></label><label>应用方向（中文） <textarea v-model.trim="form.applicationZh" /></label><label>应用方向（英文） <textarea v-model.trim="form.applicationEn" /></label><ImageUploadField :key="imageFieldKey" v-model="form.imageUrl" label="系列主图" scene="SERIES" /><label>图片说明（中文） <input v-model.trim="form.imageAltZh" placeholder="用于中文页面的图片说明" /></label><label>图片说明（英文） <input v-model.trim="form.imageAltEn" placeholder="用于英文页面的图片说明" /></label><label>SEO Title <input v-model.trim="form.seoTitle" maxlength="255" /></label><label>SEO Description <textarea v-model.trim="form.seoDescription" maxlength="1000" /></label><label><span>排序 <span class="required-mark" aria-hidden="true">*</span></span><input v-model.number="form.sortOrder" type="number" required /></label><label><span>发布状态 <span class="required-mark" aria-hidden="true">*</span></span><select v-model="form.publishStatus" required><option disabled value="">请选择发布状态</option><option value="DRAFT">草稿</option><option value="PUBLISHED">已发布</option><option value="OFFLINE">已下线</option></select></label><div class="actions"><button class="primary">{{ editingId ? "保存" : "新增系列" }}</button><button v-if="editingId" type="button" @click="cancelEdit">取消</button></div><p v-if="error" class="error">{{ error }}</p></form>
      <section class="card"><h2>系列列表</h2><table><thead><tr><th>产品系列</th><th>排序</th><th>发布状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in seriesList" :key="Number(item.id)"><td><strong>{{ item.name_zh }}</strong></td><td>{{ item.sort_order }}</td><td><span class="status">{{ statusLabel(item.publish_status) }}</span></td><td class="actions"><button @click="edit(item)">编辑</button><button @click="manageProducts(item)">管理产品</button><button @click="toggle(item)">{{ item.publish_status === "PUBLISHED" ? "下线" : "发布" }}</button><button class="danger" @click="remove(item)">删除</button></td></tr></tbody></table></section>
    </div>
  </AdminShell>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import AdminShell from "../components/AdminShell.vue";
import ImageUploadField from "../components/ImageUploadField.vue";
import { adminCreateSeries, adminDeleteSeries, adminListCategories, adminListSeries, adminUpdateSeries, adminUpdateSeriesStatus } from "../api/site";
import { useAdminFeedback } from "../composables/useAdminFeedback";
import { createUrlIdentifier } from "../utils/adminSlug";
const route = useRoute(); const router = useRouter(); const categories = ref<Array<Record<string, unknown>>>([]); const seriesList = ref<Array<Record<string, unknown>>>([]); const categoryFilter = ref(Number(route.query.categoryId || 0)); const editingId = ref<number | null>(null); const imageFieldKey = ref(0); const error = ref("");
const feedback = useAdminFeedback();
const initial = () => ({ categoryId: categoryFilter.value || 1, slug: "", nameZh: "", nameEn: "", summaryZh: "", summaryEn: "", applicationZh: "", applicationEn: "", seoTitle: "", seoDescription: "", sortOrder: null as number | null, publishStatus: "", imageUrl: "", imageAltZh: "", imageAltEn: "" }); const form = reactive(initial());
const load = async () => { seriesList.value = await adminListSeries(categoryFilter.value || undefined); };
const reset = () => { editingId.value = null; Object.assign(form, initial()); imageFieldKey.value += 1; };
const statusLabel = (status: unknown) => ({ DRAFT: "草稿", PUBLISHED: "已发布", OFFLINE: "已下线" }[String(status)] || "未知");
const startNew = () => { reset(); feedback.info("已切换到新建系列。"); };
const cancelEdit = () => { reset(); feedback.info("已取消编辑。"); };
const edit = (item: Record<string, unknown>) => { editingId.value = Number(item.id); Object.assign(form, { categoryId: item.category_id, slug: item.slug, nameZh: item.name_zh, nameEn: item.name_en || item.name_zh, summaryZh: item.summary_zh ?? "", summaryEn: item.summary_en ?? item.summary_zh ?? "", applicationZh: item.application_zh ?? "", applicationEn: item.application_en ?? item.application_zh ?? "", seoTitle: item.seo_title ?? "", seoDescription: item.seo_description ?? "", sortOrder: item.sort_order, publishStatus: item.publish_status, imageUrl: item.image_url ?? "", imageAltZh: item.image_alt_zh ?? "", imageAltEn: item.image_alt_en ?? item.image_alt_zh ?? "" }); imageFieldKey.value += 1; feedback.info("已进入系列编辑状态。"); };
const submit = async () => { error.value = ""; try { const wasEditing = Boolean(editingId.value); form.nameEn ||= form.nameZh; form.summaryEn ||= form.summaryZh; form.applicationEn ||= form.applicationZh; form.imageAltEn ||= form.imageAltZh; if (editingId.value) await adminUpdateSeries(editingId.value, { ...form }); else { form.slug = createUrlIdentifier(form.nameEn); if (!form.slug) throw new Error("invalid English name"); await adminCreateSeries({ ...form }); } reset(); await load(); feedback.success(wasEditing ? "系列保存成功。" : "系列新增成功。"); } catch { error.value = "保存失败，请确认所属分类和必填字段；英文名称不能与同分类下的现有系列重复。"; feedback.error(error.value); } };
const toggle = async (item: Record<string, unknown>) => { try { const publishing = item.publish_status !== "PUBLISHED"; await adminUpdateSeriesStatus(Number(item.id), publishing ? "PUBLISHED" : "OFFLINE"); await load(); feedback.success(publishing ? "系列发布成功。" : "系列下线成功。"); } catch { feedback.error("状态更新失败，请稍后重试。"); } };
const remove = async (item: Record<string, unknown>) => { if (!globalThis.confirm(`确定删除系列“${String(item.name_zh)}”吗？该系列下的产品也将被删除。`)) return; try { await adminDeleteSeries(Number(item.id)); if (editingId.value === Number(item.id)) reset(); await load(); feedback.success("系列删除成功。"); } catch { feedback.error("系列删除失败，请稍后重试。"); } };
const manageProducts = (item: Record<string, unknown>) => router.push({ name: "admin-product-details", params: { lang: route.params.lang }, query: { categoryId: String(item.category_id), seriesId: String(item.id) } });
onMounted(async () => { categories.value = await adminListCategories(); if (!form.categoryId && categories.value[0]) form.categoryId = Number(categories.value[0].id); await load(); });
</script>

<style scoped>
.toolbar,.actions { display:flex; flex-wrap:wrap; gap:8px; align-items:center; }.toolbar label { display:flex; gap:8px; align-items:center; }.layout { display:grid; grid-template-columns:360px 1fr; gap:18px; align-items:start; }.card { border:1px solid #e2e8f0; border-radius:12px; padding:18px; background:#fff; }.form { display:grid; gap:11px; }.form label { display:grid; gap:5px; color:#334155; font-size:.88rem; font-weight:600; }.required-mark { margin-left:2px; color:#dc2626; } input,select,textarea { border:1px solid #cbd5e1; border-radius:7px; padding:8px 10px; font:inherit; } textarea { min-height:60px; } button { border:1px solid #cbd5e1; border-radius:6px; padding:7px 9px; background:#fff; cursor:pointer; }.primary { background:#2563eb; border-color:#2563eb; color:#fff; }.danger { border-color:#fecaca; color:#b91c1c; }.error { color:#b91c1c; } table { width:100%; border-collapse:collapse; } th,td { border-top:1px solid #e2e8f0; padding:11px 8px; text-align:left; vertical-align:top; } th,small { color:#64748b; font-size:.8rem; } strong,small { display:block; margin-top:3px; }.status { color:#1d4ed8; font-size:.8rem; font-weight:700; } @media(max-width:800px){.layout{grid-template-columns:1fr;}}
</style>