-- Complete P0 product hierarchy content fields.

SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_category' AND column_name='chemical_formula')=0, 'ALTER TABLE product_category ADD COLUMN chemical_formula VARCHAR(128) NULL AFTER name_en', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_category' AND column_name='application_zh')=0, 'ALTER TABLE product_category ADD COLUMN application_zh TEXT NULL AFTER summary_en', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_category' AND column_name='application_en')=0, 'ALTER TABLE product_category ADD COLUMN application_en TEXT NULL AFTER application_zh', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_category' AND column_name='seo_title')=0, 'ALTER TABLE product_category ADD COLUMN seo_title VARCHAR(255) NULL AFTER application_en', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_category' AND column_name='seo_description')=0, 'ALTER TABLE product_category ADD COLUMN seo_description VARCHAR(1000) NULL AFTER seo_title', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_series' AND column_name='application_zh')=0, 'ALTER TABLE product_series ADD COLUMN application_zh TEXT NULL AFTER summary_en', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_series' AND column_name='application_en')=0, 'ALTER TABLE product_series ADD COLUMN application_en TEXT NULL AFTER application_zh', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_series' AND column_name='seo_title')=0, 'ALTER TABLE product_series ADD COLUMN seo_title VARCHAR(255) NULL AFTER application_en', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product_series' AND column_name='seo_description')=0, 'ALTER TABLE product_series ADD COLUMN seo_description VARCHAR(1000) NULL AFTER seo_title', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product' AND column_name='application_scenario_zh')=0, 'ALTER TABLE product ADD COLUMN application_scenario_zh TEXT NULL AFTER detail_en', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product' AND column_name='application_scenario_en')=0, 'ALTER TABLE product ADD COLUMN application_scenario_en TEXT NULL AFTER application_scenario_zh', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product' AND column_name='seo_title')=0, 'ALTER TABLE product ADD COLUMN seo_title VARCHAR(255) NULL AFTER application_scenario_en', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='product' AND column_name='seo_description')=0, 'ALTER TABLE product ADD COLUMN seo_description VARCHAR(1000) NULL AFTER seo_title', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
